background #1b110a
foreground #ffffff

cursor #f0eeff

color0  #463930
color1  #ffece9
color2  #f0eeff
color3  #c2fed7
color4  #b7beff
color5  #e0f8c9
color6  #b3ca9e
color7  #ffffff

color8  #ffece2
color9  #ffaea4
color10 #dfe0ff
color11 #96cfab
color12 #3a4281
color13 #d3eabc
color14 #e0f8c9
color15 #000000
