include theme.conf


font_family      InputMonoNarrow-Medium
bold_font        MapleMono-Bold
italic_font      MapleMono-Italic
bold_italic_font MapleMono-BoldItalic

font_size 13


# Url Settings
# url_color #61afef

url_style curly

allow_remote_control yes

### Performance tuning ###

repaint_delay 10

input_delay 3


## TAB BAR ##

tab_bar_style powerline


