include theme.conf


font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto


allow_remote_control yes

### Performance tuning ###

repaint_delay 10

input_delay 3


## TAB BAR ##

tab_bar_style powerline


remember_window_size yes
initial_window_width 129
initial_window_height 32
