# --- Main Colors ---
background            #0e1513
foreground            #dde4e1
cursor                #dde4e1
cursor_text_color     #0e1513

selection_background  #20514a
selection_foreground  #bceee5

url_color             #dac0ff

# --- ANSI Colors ---
color0                #0e1513
color1                #ffb4ab
color2                #dac0ff
color3                #9fd0c7
color4                #4ee0ce
color5                #d6baff
color6                #9fd0c7
color7                #dde4e1

color8                #3c4947
color9                #93000a
color10               #c39efc
color11               #20514a
color12               #22c4b3
color13               #1d4e48
color14               #56348a
color15               #bbcac6

# --- Starship Prompt Bubbles ---
color255              #22c4b3
color254              #4ee0ce
color253              #20514a
color252              #9fd0c7
color251              #c39efc
color250              #dac0ff
color249              #93000a
color248              #ffb4ab

color232              #002a25
color233              #003732
color234              #bceee5
color235              #003732
color236              #320865
color237              #3f1a72
color238              #ffdad6
color239              #690005
color240              #002a25

# Matched with unthemed light/dark
color243              #4ee0ce
color244              #ffb4ab
color245              #3c4947

# --- UI Elements ---
active_tab_foreground   #4ee0ce
active_tab_background   #003732
inactive_tab_foreground #002a25
inactive_tab_background #22c4b3

active_border_color     #4ee0ce
inactive_border_color   #859490

# --- Marks ---
mark1_foreground        #00201c
mark1_background        #6bf9e6
mark2_foreground        #00201c
mark2_background        #baede3
mark3_foreground        #280056
mark3_background        #ecdcff
