# --- Main Colors ---
background            #19120d
foreground            #f0dfd7
cursor                #f0dfd7
cursor_text_color     #19120d

selection_background  #5b4130
selection_foreground  #ffdcc6

url_color             #c9ca93

# --- ANSI Colors ---
color0                #19120d
color1                #ffb4ab
color2                #c9ca93
color3                #e5bfa8
color4                #ffb786
color5                #c9ca93
color6                #e5bfa8
color7                #f0dfd7

color8                #52443c
color9                #93000a
color10               #48491f
color11               #5b4130
color12               #6e390e
color13               #5b4130
color14               #48491f
color15               #d7c3b7

# --- Starship Prompt Bubbles ---
color255              #6e390e
color254              #ffb786
color253              #5b4130
color252              #e5bfa8
color251              #48491f
color250              #c9ca93
color249              #93000a
color248              #ffb4ab

color232              #ffdcc6
color233              #502400
color234              #ffdcc6
color235              #422b1b
color236              #e6e6ad
color237              #31320a
color238              #ffdad6
color239              #690005
color240              #ffdcc6

# Matched with unthemed light/dark
color243              #ffb786
color244              #ffb4ab
color245              #52443c

# --- UI Elements ---
active_tab_foreground   #502400
active_tab_background   #ffb786
inactive_tab_foreground #ffdcc6
inactive_tab_background #6e390e

active_border_color     #ffb786
inactive_border_color   #9f8d83

# --- Marks ---
mark1_foreground        #311300
mark1_background        #ffdcc6
mark2_foreground        #2b1708
mark2_background        #ffdcc6
mark3_foreground        #1c1d00
mark3_background        #e6e6ad
