[ColorScheme]
active_foreground=#ffffff
active_background=#b5ffe5
inactive_foreground=#ffffff
inactive_background=#3f4945
button_foreground=#000000
button_background=#b5ffe5
selection_foreground=#000000
selection_background=#dbf6ea
tooltip_foreground=#ffffff
tooltip_background=#0f1512
